### PR TITLE
proposal to add support for Child metrics in prometheus

### LINKED ISSUE #75: Add Child metrics support for Prometheus API
Currently, Prometheus API does not support Child metrics out of the box. In order to use `Child` and gain performance benefits I have to do the following trick: 

```
   for {
      ss <- registerSummary(name = "db_duration_seconds" ... )
      res = new Service {
           def callSucccess:UIO[Summary.Child] = Task(ss.labels("success")).orDie
           ....
    }
```

I propose to add a wrapper for each `Child` metrics in order to integrate it with `ZIO` smoothly. With this new wrapper, I would be able to at least wrap `ss.labels("success")` manually here.

Here is a draft example: #74

### PR DESCRIPTION
**Pull request by heaven-born**
Closes #75

Propose to add Child for each metric in order to support [recommended](https://www.robustperception.io/label-lookups-and-the-child) way of working with labels.

### CODE REVIEW

**Comment by toxicafunk** [comment]
@heaven-born can you please run `sbt fmt check` and push your changes after that? 

Thanks

**Comment by heaven-born** [comment]
@toxicafunk I've planned to add the rest of the classes not only for a summary. Just wanted to make sure that it looks like something that is acceptable to put into this project.

**Comment by toxicafunk** [comment]
Yes, definitely, no adding child support is mostly an overlook from my part. 

You might also be interested in this branch with an alternate Prometheus API : https://github.com/zio/zio-metrics/tree/prometheus2

I'd say, lets first add your PR to the normal branch and then see how to integrate them to the new one.

**Comment by heaven-born** [comment]
@toxicafunk I've added the rest of the child metrics, so it is officially not a draft anymore. The pull request still has a "draft" mark because I don't know how to remove it)

**Review by toxicafunk — APPROVED** [review]

**Pull request merged**
