### PR TITLE
Update to latest zio/nio

### PR DESCRIPTION
**Pull request by impatient**

### CODE REVIEW

**Comment by impatient** [comment]
The lint is failing on this error. It doesn't look like I can restart the job.
```
Downloading sbt launcher for 1.3.8:
  From  http://repo.scala-sbt.org/scalasbt/maven-releases/org/scala-sbt/sbt-launch/1.3.8/sbt-launch.jar
    To  /home/circleci/.sbt/launchers/1.3.8/sbt-launch.jar
Download failed. Obtain the jar manually and place it at /home/circleci/.sbt/launchers/1.3.8/sbt-launch.jar
```

**Comment by mijicd** [comment]
@impatient please update the sbt launcher and push. That should solve everything.

**Comment by impatient** [comment]
I changed it to 1.4.2, since that's what 's on the main ZIO project. FWIW I tried the same sbt from the original error and it resolved for me.

**Comment by mijicd** [comment]
@impatient I meant take the one from https://github.com/paulp/sbt-extras and update the existing :).

**Review by mijicd — APPROVED** [review]

**Pull request merged**
