### PR TITLE
zio2 RC6

### PR DESCRIPTION
**Pull request by justcoon**
migration to ZIO2 RC6

### CODE REVIEW

**Comment by Fristi** [comment]
Is this released somewhere @justcoon ?

**Comment by justcoon** [comment]
@Fristi , probably not

@toxicafunk can you release this version?

**Comment by toxicafunk** [comment]
Should be released now. Sorry for the delay.

**Comment by Fristi** [comment]
At which repository has this been published?

**Comment by toxicafunk** [comment]
There was an error at the publishing step, but its fixed now!
```
coursier fetch dev.zio::zio-metrics-prometheus:2.0.0-RC6
https://repo1.maven.org/maven2/dev/zio/zio-metrics-prometheus_2.13/2.0.0-RC6/zio-metrics-prometheus_2.…
  100.0% [##########] 3.7 KiB (7.3 KiB / s)
https://repo1.maven.org/maven2/io/prometheus/simpleclient/0.12.0/simpleclient-0.12.0.pom
  100.0% [##########] 1.9 KiB (26.6 KiB / s)
```

**Pull request merged**
